name: UbuntuAction
on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04,ubuntu-18.04]
        qt_ver: [5.9.8,5.12.6]
    steps:
      - name: Install Qt
        if: steps.cacheqt.outputs.cache-hit != 'true'
        uses: jurplel/install-qt-action@v2.0.0
        with:
          # Directory to install Qt
          #dir: # optional
          # Version of Qt to install
          version: ${{ matrix.qt_ver }}
          # optional, default is 5.12.6
          # Host platform
          #host: # optional
          # Target platform for build
          #target: # optional, default is desktop
          # Architecture for Windows/Android
          #arch: # optional
      - name: ubuntu install GL library
        run: sudo apt-get install -y libglew-dev libglfw3-dev
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build ubuntu
        run: |
          export PATH=$PATH:$Qt5_Dir
          qmake
          make
      - name: CacheQt
        uses: actions/cache@v1
        if: matrix.qt_ver == '5.12.6'
        with:
          path: ${{ env.Qt5_Dir }}
          key: ${{ runner.OS }}-Qt-${{ matrix.qt_ver }}